# Generated by Django 2.2.3 on 2019-07-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hourly_rate', models.FloatField(default=15.0)),
                ('company', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=5000)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
    ]
