# Generated by Django 2.2.3 on 2019-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salon_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='salon_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
